server:
  port: 8090

spring:
  application:
    name: employee-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:stock
    driverClassName: org.h2.Driver
    username: sa
    password:
